# source 'https://github.com/CocoaPods/Specs.git'
source 'git@git.qutoutiao.net:lechuan/LCSpec.git'             # 其它集团库
source 'git@git.qutoutiao.net:lechuan/InnoAntiSpamSpecs.git'  # Antispam仓库
source 'git@git.qutoutiao.net:media/podspec.media.git'

platform :ios, '11.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

use_frameworks!

target 'LuckyDeal' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  pod 'InnoAntiSpamSDK', '~> 2.5.6.200401'
  pod 'InnoSecureSDK', '3.3.2.200707'
  pod 'Alamofire', '~> 5.0.0-rc.3'
  pod 'FMDB'
  pod 'SwiftyJSON', '~> 5.0'
  pod 'HandyJSON', '~> 5.0.1'
  pod 'AppsFlyerFramework'
  pod 'Bugly'
  pod 'InnotechIMSDK/Push', '1.2.0'  
  pod 'react-native-branch', path: '../node_modules/react-native-branch'
  pod 'Zip', '~> 1.1'
  pod 'FLEX', :configurations => ['Debug']
  pod 'WHDebugTool', '~> 2.1', :configurations => ['Debug']
  pod "IQKeyboardManager"
  pod 'HappyDNS'
  pod 'SocketRocket'
  pod 'JSONModel'
  pod 'Masonry'
  pod 'SDWebImage'
  pod 'TZImagePickerController'
  pod 'MJRefresh'
  pod 'Flurry-iOS-SDK/FlurrySDK'

  use_native_modules!

  pre_install do |installer|
    # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
  end

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
      end
    end
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
#  add_flipper_pods!
#  post_install do |installer|
#    flipper_post_install(installer)
#  end
end

